web/lesson10/quoteapp/urls.py
from django.urls import path

from . import views as v


app_name = 'quoteapp'

urlpatterns = [
    path('', v.main, name='main'),
    path('page/<int:page>', v.main, name='main_paginate'),
    path('author/<str:author_name>', v.author_detail, name='author_detail'),
    path('tag/<str:tag_name>/', v.quotes_by_tag, name='quotes_by_tags'),
    path('tag/<str:tag_name>/page/<int:page>/', v.quotes_by_tag, name='quotes_by_tags_paginate'),
    path('quote/', v.quote, name='quote'),
    path('add-author/', v.author, name='author'),
]

web/lesson10/quotes/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('quoteapp.urls')),
    path('users/', include('users.urls')),
]

web/lesson10/users/urls.py
from django.contrib.auth.views import PasswordResetDoneView, PasswordResetCompleteView, PasswordResetConfirmView
from django.urls import path

from . import views as v


app_name = 'users'

urlpatterns = [
    path('signup/', v.signupuser, name='signup'),
    path('login/', v.loginuser, name='login'),
    path('logout/', v.logoutuser, name='logout'),
    path('reset-password/', v.ResetPasswordView.as_view(), name='password_reset'),
    path(
        'reset-password/done/',
        PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
        name='password_reset_done'
    ),
    path(
        'reset-password/confirm/<uidb64>/<token>/',
        PasswordResetConfirmView.as_view(
            template_name='users/password_reset_confirm.html',
            success_url='/users/reset-password/complete/'
        ),
        name='password_reset_confirm'
    ),
    path(
        'reset-password/complete/',
        PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
        name='password_reset_complete'
    ),
]

web/lesson10/quoteapp/models.py
from django.db import models as m


class Author(m.Model):
    fullname = m.CharField(max_length=50)
    born_date = m.CharField(max_length=50)
    born_location = m.CharField(max_length=150)
    description = m.TextField()
    created_at = m.DateTimeField(auto_now_add=True)


class Tag(m.Model):
    name = m.CharField(max_length=50, null=False, unique=True)


class Quote(m.Model):
    quote = m.TextField()
    tags = m.ManyToManyField(Tag)
    author = m.ForeignKey(Author, on_delete=m.CASCADE, null=True)
    created_at = m.DateTimeField(auto_now_add=True)

web/lesson10/quoteapp/forms.py
from django.forms import CharField, ModelForm, TextInput

from .models import Author, Quote


class QuoteForm(ModelForm):
    quote = CharField()

    class Meta:
        model = Quote
        fields = ['quote', ]
        exclude = ['tags', 'author', ]


class AuthorForm(ModelForm):
    fullname = CharField(max_length=50, required=True, widget=TextInput())
    born_date = CharField(max_length=50)
    born_location = CharField(max_length=150)
    description = CharField()

    class Meta:
        model = Author
        fields = ['fullname', 'born_date', 'born_location', 'description', ]

web/lesson10/quoteapp/views.py
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404, redirect, render

from .forms import AuthorForm, QuoteForm
from .models import Author, Quote, Tag


def main(request, page=1):
    quotes = Quote.objects.all()

    per_page = 10
    paginator = Paginator(list(quotes), per_page)
    quotes_on_page = paginator.page(page)

    context = {
        'quotes': quotes_on_page,
    }

    return render(request, 'quoteapp/index.html', context=context)


@login_required
def quote(request):
    tags = Tag.objects.all()
    all_authors = Author.objects.all()

    if request.method == 'POST':
        form = QuoteForm(request.POST)

        if form.is_valid():
            new_quote = form.save()
            choice_tags = Tag.objects.filter(name__in=request.POST.getlist('tags'))

            for tag in choice_tags.iterator():
                new_quote.tags.add(tag)

            new_quote.author = Author.objects.get(id=request.POST.get('author'))
            new_quote.save()

            return redirect(to='quoteapp:main')

        else:
            context = {
                'tags': tags,
                'all_authors': all_authors,
                'form': form,
            }

            return render(request, 'quoteapp/quote.html', context)

    context = {
        'tags': tags,
        'all_authors': all_authors,
        'form': QuoteForm(),
    }
    return render(request, 'quoteapp/quote.html', context)


@login_required
def author(request):
    if request.method == 'POST':
        form = AuthorForm(request.POST)

        if form.is_valid():
            new_author = form.save()
            new_author.save()

            return redirect(to='quoteapp:main')

        else:
            return render(request, 'quoteapp/author.html', {'form': form})

    return render(request, 'quoteappp/author.html', {'form': AuthorForm()})


def author_detail(request, author_name):
    author = get_object_or_404(Author, fullname=author_name)

    return render(request, 'quoteapp/author_detail.html', {'author': author})


def quotes_by_tag(request, tag_name, page=1):
    tag = get_object_or_404(Tag, name=tag_name)
    quotes = Quote.objects.filter(tags=tag)

    per_page = 10
    paginator = Paginator(list(quotes), per_page)
    quotes_on_page = paginator.page(page)
    
    context = {
        'tag': tag,
        'quotes': quotes_on_page,
    }

    return render(request, 'quoteapp/tag.html', context)

web/lesson10/quoteapp/templates/quoteapp/author.html
{% extends "quoteapp/base.html" %}

{% block content %}
<h1 class="text-light mb-3"> Adding author</h1>
<form method="POST" action="{% url 'quoteapp:author' %}">
    {% csrf_token %}
    <div class="row">
        <div class="col mb-3">
            <label class="form-label text-light">
                <strong>Fullname:</strong>
            </label>
        </div>
        <div class="col mb-3">
            <div>{{ form.fullname }}</div>
            {% if form.errors.name %}
            <span class="text-warning"><small>{{ form.errors.name }}</small></span>
            {% endif %}
        </div>
    </div>
    <div class="row">
        <div class="col mb-3">
            <label class="form-label text-light">
                <strong>Born date:</strong>
            </label>
            <div>{{ form.born_date }}</div>
            {% if form.errors.name %}
            <span class="text-warning"><small>{{ form.errors.name }}</small></span>
            {% endif %}
        </div>
    </div>
    <div class="row">
        <div class="col mb-3">
            <label class="form-label text-light">
                <strong>Born location:</strong>
            </label>
            <div>{{ form.born_location }}</div>
            {% if form.errors.name %}
            <span class="text-warning"><small>{{ form.errors.name }}</small></span>
            {% endif %}
        </div>
    </div>
    <div class="row">
        <div class="col mb-3">
            <label class="form-label text-light">
                <strong>Description:</strong>
            </label>
            <div>{{ form.description }}</div>
            {% if form.errors.name %}
            <span class="text-warning"><small>{{ form.errors.name }}</small></span>
            {% endif %}
        </div>
    </div>
    <div class="row mt-3">
        <div class="col">
            <button type="submit" class="btn btn-primary">Submit</button>
            <button type="reset" class="btn btn-secondary">Reset</button>
        </div>
    </div>
</form>
{% endblock %}

web/lesson10/quoteapp/templates/quoteapp/author_detail.html
{% extends "quoteapp/base.html" %} {% block content %}

<div class="author-details">
    <h3 class="author-title">{{author.fullname}}</h3>
    <p><strong>Born:</strong> <span class="author-born-date">{{author.born_date}}</span> <span
            class="author-born-location">{{author.born_location}}</span></p>
    <p><strong>Description:</strong></p>
    <div class="author-description">
        {{author.description}}
    </div>
</div>

{% endblock %}

web/lesson10/quoteapp/templates/quoteapp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" href="{% static 'quoteapp/bootstrap.css' %}">
    {% load static %}
    <link rel="stylesheet" href="{% static 'quoteapp/style.css' %}">
    <title>Homework</title>
</head>
<body>
<div class="container">
    <div class="row header-box pt-3 mb-3">
        <div class="col-md-8">
            <h1>
                <a href="/" style="text-decoration: none">Quotes to Scrape</a>
            </h1>
        </div>
        <div class="col-md-4">
            {% if user.is_authenticated %}
            <ul class="nav col-12 col-md-auto mb-2 justify-content-center mb-md-0">
                <li><a class="btn nav-link px-2 link-light" href="{% url 'quoteapp:quote' %}">Add new quote</a></li>
{#                <li><a class="btn nav-link px-2 link-light" href="{% url 'quoteapp:author' %}">Add new author</a></li>#}
            </ul>
            {% endif %}
        </div>
        <div class="col-md-4">
            <p>
                {% if user.is_authenticated %}
                <span>
                Welcome <b>{{ user.username }}!</b>
            </span>
                <a href="{% url 'users:logout' %}">
                    <button type="button" class="btn btn-danger"> Logout</button>
                </a>
                {% else %}
                <a href="{% url 'users:signup' %}">
                    <button type="button" class="btn btn-primary">SignUp</button>
                </a>
                <a href="{% url 'users:login' %}">
                    <button type="button" class="btn btn-primary"> Login</button>
                </a>
                {% endif %}
            </p>
        </div>
    </div>

    {% block content %}
    {% endblock %}

</div>
</body>
</html>

web/lesson10/quoteapp/templates/quoteapp/index.html
{% extends 'quoteapp/base.html' %}
{% load extract %}

{% block content %}

<div class="row">
    <div class="col-md-8">

        {% for quote in quotes %}
            <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
                <span class="text" itemprop="text">
                    {{ quote.quote }}
                </span>

                <span>by <small class="author" itemprop="author">{{quote.author.fullname}}</small>
                    <a href="/author/{{quote.author.fullname}}">(about)</a>
                </span>

                <div class="tags">
                    Tags:
                    {% for tag in quote.tags.all %}
                        <a class="tag" href="/tag/{{tag.name}}">{{tag.name}}</a>
                    {% endfor %}
                </div>
            </div>
        {% endfor %}

         <nav>
            <ul class="pager">
                {% if quotes.has_previous %}
                <li class="previous">
                    <a href="{% url 'quoteapp:main_paginate' quotes.previous_page_number %}">
                        <span aria-hidden="true">←</span> Previous
                    </a>
                </li>
                {% endif %}
                {% if quotes.has_next %}
                <li class="next">
                    <a href="{% url 'quoteapp:main_paginate' quotes.next_page_number %}">Next
                        <span aria-hidden="true">→</span>
                    </a>
                </li>
                {% endif %}
            </ul>
        </nav>
    </div>
</div>

{% endblock %}

web/lesson10/quoteapp/templates/quoteapp/quote.html
{% extends "quoteapp/base.html" %}

{% block content %}
<h1 class="text-light mb-3"> Adding quote</h1>
<form method="POST" action="{% url 'quoteapp:quote' %}">
    {% csrf_token %}
    <div class="row">
        <div class="col mb-3">
            <label class="form-label text-light">
                <strong>Quote:</strong>
            </label>
            <div>{{ form.quote }}</div>
            {% if form.errors.name %}
            <span class="text-warning"><small>{{ form.errors.name }}</small></span>
            {% endif %}
        </div>
    </div>
    <div class="row">
        <div class="mb-3 col">
            <label class="form-label text-light"><strong>Quote author:</strong></label>
        </div>
         <div class="mb-3 col">
            <select name="author">
                {% for author in all_authors %}
                <option value="{{author.id}}">{{author.fullname}}</option>
                {% endfor %}
            </select>
        </div>
    </div>
    <div class="row">
        <div class="mb-3 col">
            <label class="form-label text-light"><strong>Select tags:</strong></label>
        </div>
        <div class="mb-3 col">
            <select name="tags" class="form-select" size="5">
                {% for tag in tags %}
                <option value="{{tag.name}}">{{tag.name}}</option>
                {% endfor %}
            </select>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <button type="submit" class="btn btn-primary">Submit</button>
            <button type="reset" class="btn btn-secondary">Reset</button>
        </div>
    </div>
</form>
{% endblock %}

web/lesson10/quoteapp/templates/quoteapp/tag.html
{% extends "quoteapp/base.html" %} {% block content %}

<div class="col-md-8">
    <h3>Viewing tag: <a href="/tag/{{tag.name}}/page/1/">{{tag.name}}</a></h3>
{% for quote in quotes %}
<div class="quote" itemscope itemtype="http://schema.org/CreativeWork">
    <span class="text" itemprop="text">{{ quote.quote}}</span>
    <span>by <small class="author" itemprop="author">{{quote.author.fullname}}</small>
        <a href="/author/{{quote.author.fullname}}">(about)</a>
        </span>
    <div class="tags">
        Tags:
        {% for tag in quote.tags.all %}
        <a class="tag" href="/tag/{{tag.name}}">{{tag.name}}</a>
        {% endfor %}


    </div>
</div>

{% endfor %}

<nav>
    <ul class="pager">
        {% if quotes.has_previous %}
        <li class="previous">
            <a href="{% url 'quoteapp:quotes_by_tags_paginate' tag.name quotes.previous_page_number %}">
                <span aria-hidden="true">←</span> Previous
            </a>
        </li>
        {% endif %}
        {% if quotes.has_next %}
        <li class="next">
            <a href="{% url 'quoteapp:quotes_by_tags_paginate' tag.name quotes.next_page_number %}">Next
                <span aria-hidden="true">→</span>
            </a>
        </li>
        {% endif %}
    </ul>
</nav>
</div>
{% endblock %}